print("============================================================")
print("  GRAND MARINA WATER MONITORING DASHBOARD")
print("  Connected successfully")
print("============================================================")
print()
print("Listening for sensor readings...")
print()
print("────────────────────────────────────────")
print("  Location:  main-building")
print("  Device ID: GM-HYDROLOGIC-01")
print("  Time:      2026-01-15T14:30:47.123456+00:00")
print("  Count:     #1")
print("────────────────────────────────────────")
print("  Pressure (upstream):    82.3 PSI")
print("  Pressure (downstream):  76.8 PSI")
print("  Flow rate:              41.2 gal/min")
print("  Pressure differential:   5.5 PSI")