# =============================================================================
# Mosquitto Configuration: TLS SECURED
# =============================================================================

listener 8883 localhost

cafile certs/ca.pem
certfile certs/server.pem
keyfile certs/server-key.pem

require_certificate false
allow_anonymous true

log_type all
log_dest stdout

max_queued_messages 1000